stages:
  - build
  - deploy
  - rollback

variables:
  CI_REGISTRY_USER: $REGISTRY_USER
  CI_REGISTRY_PASSWORD: $REGISTERY_PASS
  CI_REGISTRY: zyadzarin
  BACKEND_IMAGE: $CI_REGISTRY/olympic2024-dashboard-backend
  NGINX_IMAGE: $CI_REGISTRY/olympic2024-dashboard-nginx
  VM_IP: 206.189.89.80
  DEPLOY_PATH: /home/root/olympic2024-dashboard

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA -t $BACKEND_IMAGE:latest -f docker/backend/Dockerfile .
    - docker push $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $BACKEND_IMAGE:latest
    - docker build -t $NGINX_IMAGE:$CI_COMMIT_SHORT_SHA -t $NGINX_IMAGE:latest -f docker/nginx/Dockerfile .
    - docker push $NGINX_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $NGINX_IMAGE:latest
  only:
    - main

deploy:
  stage: deploy
  image: ubuntu:22.04
  needs:
    - build
  before_script:
    - apt-get update -qq && apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo $SSH_HOST_KEY >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp docker-compose.yml root@$VM_IP:$DEPLOY_PATH/docker-compose.yml
    - ssh root@$VM_IP "
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD &&
        export BACKEND_IMAGE=$BACKEND_IMAGE &&
        export NGINX_IMAGE=$NGINX_IMAGE &&
        docker-compose pull &&
        docker-compose up -d
        echo $CI_COMMIT_SHORT_SHA > last_deployed_version.txt
      "
  only:
    - main

rollback:
  stage: rollback
  image: ubuntu:22.04
  when: manual
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $DO_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - |
      ssh root@$VM_IP "
        cd $DEPLOY_PATH
        if [ -f last_deployed_version.txt ]; then
          LAST_VERSION=\$(cat last_deployed_version.txt)
          CURRENT_VERSION=$CI_COMMIT_SHORT_SHA
          if [ \"\$LAST_VERSION\" != \"\$CURRENT_VERSION\" ]; then
            docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
            export BACKEND_IMAGE=$BACKEND_IMAGE:\$LAST_VERSION &&
            export NGINX_IMAGE=$NGINX_IMAGE:\$LAST_VERSION &&
            docker-compose pull &&
            docker-compose up -d
            echo 'Rolled back to version \$LAST_VERSION'
          else
            echo 'Current version is the same as the last deployed version. No rollback needed.'
          fi
        else
          echo 'No previous version found. Cannot rollback.'
        fi
      "
  only:
    - main
    